/**
 * Offline-first expenses: IndexedDB is canonical at runtime; Supabase syncs via the durable queue.
 * UI and pages must use this (or hooks built on it), not `db.finance().from('expenses')` directly.
 */
import { AnalyticsEvents, captureEvent } from '@/lib/analytics';
import { requireCompanyId } from '@/lib/db';
import { enqueueUnifiedNotification } from '@/services/unifiedNotificationPipeline';
import {
  buildLocalRow,
  getEntityById,
  listEntitiesByCompany,
  shouldApplyRemoteRow,
  upsertEntityRow,
} from '@/lib/localData/entityRepository';
import { buildIdempotencyKey, enqueueLocalSync } from '@/lib/localData/localSyncQueue';
import {
  type CreateExpenseInput,
  type ExpenseLike,
  type FinanceExpenseRow,
  TOMATO_HARVEST_PICKER_LABOUR_EXPENSE_SOURCE,
  displayPickerPayoutExpenseNote,
  fetchRawFinanceExpenseRows,
} from '@/services/financeExpenseService';
import { isClientOnline, scheduleLocalDataSync } from '@/services/localData/shared';

const LARGE_EXPENSE_KES = 50_000;

function parsePickerPayoutNoteIds(note: string): { collectionId?: string; pickerId?: string } {
  const collectionMatch = note.match(/collection:([a-f0-9-]{36})/i);
  const pickerMatch = note.match(/picker:([a-f0-9-]{36})/i);
  return {
    collectionId: collectionMatch?.[1],
    pickerId: pickerMatch?.[1],
  };
}

function mapRowToExpenseLike(row: FinanceExpenseRow): ExpenseLike {
  const note = row.note ?? '';
  const rowSource = String(row.source ?? '');
  const isPickerPayout =
    row.category === 'picker_payout' ||
    rowSource === 'picker_payment' ||
    note.toLowerCase().includes('picker payout');
  const ids = isPickerPayout && note ? parsePickerPayoutNoteIds(note) : {};
  if (rowSource === TOMATO_HARVEST_PICKER_LABOUR_EXPENSE_SOURCE && row.reference_id) {
    const parts = (note || '').split(/\n\n+/);
    const title = (parts[0] || 'Labour (Tomato harvest)').trim();
    const labourNote = (parts[1] || 'This expense is calculated from picker activity.').trim();
    return {
      id: row.id,
      companyId: row.company_id,
      farmId: row.farm_id,
      projectId: row.project_id ?? undefined,
      category: row.category,
      description: title,
      amount: Number(row.amount ?? 0),
      date: row.expense_date,
      createdAt: row.created_at,
      autoGenerated: true,
      meta: {
        source: TOMATO_HARVEST_PICKER_LABOUR_EXPENSE_SOURCE,
        tomatoHarvestSessionId: row.reference_id ?? undefined,
        autoGenerated: true,
        harvestPickerLabourNote: labourNote,
      },
    };
  }
  const autoGen = Boolean(row.auto_generated);
  const rawDesc = (row.note || row.category || 'Expense').trim() || 'Expense';
  if (isPickerPayout) {
    const head = displayPickerPayoutExpenseNote(note);
    return {
      id: row.id,
      companyId: row.company_id,
      farmId: row.farm_id,
      projectId: row.project_id ?? undefined,
      category: row.category,
      description: head,
      amount: Number(row.amount ?? 0),
      date: row.expense_date,
      createdAt: row.created_at,
      autoGenerated: autoGen || undefined,
      meta: {
        source: 'harvest_wallet_picker_payment',
        harvestCollectionId: ids.collectionId,
        pickerId: ids.pickerId,
      },
    };
  }
  return {
    id: row.id,
    companyId: row.company_id,
    farmId: row.farm_id,
    projectId: row.project_id ?? undefined,
    category: row.category,
    description: rawDesc,
    amount: Number(row.amount ?? 0),
    date: row.expense_date,
    createdAt: row.created_at,
    autoGenerated: autoGen || undefined,
  };
}

function buildInsertRow(
  id: string,
  input: CreateExpenseInput,
): Record<string, unknown> {
  const expenseDate = input.expenseDate ?? new Date().toISOString().slice(0, 10);
  const insertRow: Record<string, unknown> = {
    id,
    company_id: input.companyId,
    farm_id: input.farmId,
    project_id: input.projectId ?? null,
    category: input.category,
    amount: input.amount,
    currency: 'KES',
    expense_date: expenseDate,
    note: input.note ?? null,
    created_by: input.createdBy ?? null,
  };
  if (input.source != null && String(input.source).trim()) {
    insertRow.source = String(input.source).trim();
  }
  if (input.referenceId != null && String(input.referenceId).trim()) {
    insertRow.reference_id = String(input.referenceId).trim();
  }
  return insertRow;
}

export const ExpenseService = {
  /**
   * Read from the local store only — instant, never blocked by network.
   * Call {@link pullRemote} when online to hydrate from Supabase.
   */
  async list(
    companyId: string,
    options?: { farmId?: string | null; projectId?: string | null },
  ): Promise<ExpenseLike[]> {
    if (!companyId) return [];
    const cid = requireCompanyId(companyId);
    const farmId = options?.farmId ?? null;
    const projectId = options?.projectId ?? null;
    const rows = await listEntitiesByCompany('expenses', cid);
    const mapped = rows
      .map((e) => e.data as unknown as FinanceExpenseRow)
      .filter((r) => r && r.id)
      .filter((r) => (farmId ? r.farm_id === farmId : true))
      .filter((r) => (projectId ? r.project_id === projectId : true));
    return mapped.map((r) => mapRowToExpenseLike(r));
  },

  /**
   * Background refresh from Supabase; merges into IndexedDB (last-write-wins vs pending local).
   */
  async pullRemote(
    companyId: string,
    options?: { farmId?: string | null; projectId?: string | null },
  ): Promise<void> {
    if (!isClientOnline()) return;
    const cid = requireCompanyId(companyId);
    const raw = await fetchRawFinanceExpenseRows(cid, options);
    for (const r of raw) {
      const existing = (await listEntitiesByCompany('expenses', cid)).find((x) => x.id === r.id);
      const remoteUp = r.created_at;
      if (!shouldApplyRemoteRow({ local: existing, remoteUpdatedAt: remoteUp })) {
        continue;
      }
      const d = { ...(r as unknown as Record<string, unknown>) };
      const row: Parameters<typeof buildLocalRow>[0] = {
        id: r.id,
        companyId: r.company_id,
        data: d,
        syncStatus: 'synced',
        createdAt: r.created_at,
        updatedAt: remoteUp,
      };
      await upsertEntityRow('expenses', buildLocalRow(row));
    }
  },

  /**
   * Create an expense: persisted locally and queued; sync engine pushes to `finance.expenses` when online.
   */
  async create(input: CreateExpenseInput): Promise<ExpenseLike> {
    if (String(input.source ?? '').trim() === TOMATO_HARVEST_PICKER_LABOUR_EXPENSE_SOURCE) {
      throw new Error('Tomato picker labour expenses are created automatically from harvest activity.');
    }
    const tenant = requireCompanyId(input.companyId);
    const id = crypto.randomUUID();
    const t = new Date().toISOString();
    const insertRow = { ...buildInsertRow(id, { ...input, companyId: tenant }), created_at: t } as Record<
      string,
      unknown
    >;
    const local = buildLocalRow({
      id,
      companyId: tenant,
      data: insertRow,
      syncStatus: 'pending',
      createdAt: t,
      updatedAt: t,
    });
    await upsertEntityRow('expenses', local);
    const queueId = crypto.randomUUID();
    await enqueueLocalSync({
      id: queueId,
      action_type: 'ADD_EXPENSE',
      table_name: 'expenses',
      company_id: tenant,
      payload: { row: insertRow, id, company_id: tenant },
      idempotency_key: buildIdempotencyKey('ADD_EXPENSE', 'expenses', id),
    });
    scheduleLocalDataSync(tenant);

    const asRow = insertRow as unknown as FinanceExpenseRow;
    const like = mapRowToExpenseLike(asRow);

    captureEvent(AnalyticsEvents.EXPENSE_CREATED, {
      company_id: tenant,
      project_id: input.projectId ?? undefined,
      expense_category: input.category,
      module_name: 'expenses',
    });
    if (typeof window !== 'undefined') {
      const amt = Number(input.amount ?? 0);
      const rawNote = (String(input.note || input.category).trim() || 'Expense') as string;
      enqueueUnifiedNotification({
        tier: 'activity',
        kind: 'activity_expense_added',
        title: 'Expense recorded',
        body: `${rawNote} — KES ${Math.round(amt).toLocaleString('en-KE')}`,
        path: '/expenses',
        toastType: 'success',
      });
      if (amt >= LARGE_EXPENSE_KES) {
        enqueueUnifiedNotification({
          tier: 'insights',
          kind: 'insight_expense',
          title: 'Large expense logged',
          body: `KES ${Math.round(amt).toLocaleString('en-KE')} — ${rawNote}. Review in Expenses.`,
          path: '/expenses',
          toastType: 'warning',
        });
      }
    }
    return like;
  },

  /**
   * Update an existing expense: local store + `UPDATE_EXPENSE` queue (same offline-first model as create).
   */
  async update(
    id: string,
    input: {
      companyId: string;
      amount?: number;
      note?: string | null;
      expenseDate?: string | null;
      category?: string;
    },
  ): Promise<void> {
    if (!id?.trim()) throw new Error('Expense id is required.');
    const tenant = requireCompanyId(input.companyId);
    const existing = await getEntityById('expenses', id);
    if (!existing || existing.company_id !== tenant) {
      throw new Error('Expense not found.');
    }
    const data = { ...(existing.data as Record<string, unknown>) };
    const rowSource = String(data.source ?? '');
    if (rowSource === TOMATO_HARVEST_PICKER_LABOUR_EXPENSE_SOURCE) {
      throw new Error('This expense is maintained automatically from harvest activity and cannot be edited manually.');
    }
    if (rowSource === 'harvest_wallet_picker_payment' || rowSource === 'picker_payment') {
      throw new Error('Picker payment expenses cannot be edited here.');
    }
    if (data.auto_generated) {
      throw new Error('This system-maintained expense cannot be edited manually.');
    }

    const patch: Record<string, unknown> = {};
    if (input.amount !== undefined) patch.amount = input.amount;
    if (input.note !== undefined) patch.note = input.note;
    if (input.expenseDate !== undefined) {
      const d = String(input.expenseDate ?? '').trim();
      if (d) patch.expense_date = d;
    }
    if (input.category !== undefined) patch.category = input.category;
    if (Object.keys(patch).length === 0) return;

    const newData: Record<string, unknown> = { ...data, ...patch };
    const t = new Date().toISOString();
    const created = String((data as { created_at?: string }).created_at ?? t);
    const local = buildLocalRow({
      id,
      companyId: tenant,
      data: newData,
      syncStatus: 'pending',
      createdAt: created,
      updatedAt: t,
    });
    await upsertEntityRow('expenses', local);
    const queueId = crypto.randomUUID();
    await enqueueLocalSync({
      id: queueId,
      action_type: 'UPDATE_EXPENSE',
      table_name: 'expenses',
      company_id: tenant,
      payload: { id, company_id: tenant, patch },
      idempotency_key: buildIdempotencyKey('UPDATE_EXPENSE', 'expenses', id, t),
    });
    scheduleLocalDataSync(tenant);
  },
};

export type { CreateExpenseInput, ExpenseLike };
