import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { fvBrand } from './brand';

export type PdfMeta = {
  companyName: string;
  reportTitle: string;
  dateRangeLabel: string;
  generatedAtLabel: string;
};

function addFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  const { colors } = fvBrand;
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  doc.setFontSize(9);
  doc.setTextColor(colors.muted);
  doc.text('Generated by FarmVault', 14, h - 10);
  doc.text(`Page ${pageNumber} of ${totalPages}`, w - 14, h - 10, { align: 'right' });

  doc.setTextColor(colors.watermark);
  doc.text('FarmVault', w / 2, h - 10, { align: 'center' });
}

function headerBand(doc: jsPDF, title: string, subtitle?: string) {
  const { colors } = fvBrand;
  const w = doc.internal.pageSize.getWidth();

  doc.setFillColor(colors.bg);
  doc.rect(0, 0, w, 22, 'F');

  doc.setFont(fvBrand.font.title, 'bold');
  doc.setFontSize(14);
  doc.setTextColor(colors.greenDark);
  doc.text(title, 14, 14);

  if (subtitle) {
    doc.setFont(fvBrand.font.body, 'normal');
    doc.setFontSize(10);
    doc.setTextColor(colors.muted);
    doc.text(subtitle, 14, 19);
  }
}

export function createFarmVaultReportPdf(meta: PdfMeta) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const { colors } = fvBrand;

  // Page 1 cover
  headerBand(doc, 'FarmVault', 'Reports & Analytics');
  doc.setFont(fvBrand.font.title, 'bold');
  doc.setFontSize(22);
  doc.setTextColor(colors.text);
  doc.text(meta.reportTitle, 14, 80);

  doc.setFont(fvBrand.font.body, 'normal');
  doc.setFontSize(12);
  doc.setTextColor(colors.muted);
  doc.text(`Company: ${meta.companyName}`, 14, 105);
  doc.text(`Date range: ${meta.dateRangeLabel}`, 14, 125);
  doc.text(`Generated: ${meta.generatedAtLabel}`, 14, 145);

  return doc;
}

export function addSummaryPage(
  doc: jsPDF,
  summary: { revenue: number; expenses: number; profit: number; yield: number },
  formatKes: (n: number) => string,
  formatYield: (n: number) => string,
) {
  const { colors } = fvBrand;
  doc.addPage();
  headerBand(doc, 'Summary', 'Key performance totals');

  const cards = [
    { label: 'Revenue', value: formatKes(summary.revenue), accent: colors.green },
    { label: 'Expenses', value: formatKes(summary.expenses), accent: colors.gold },
    { label: 'Profit', value: formatKes(summary.profit), accent: colors.greenDark },
    { label: 'Yield', value: formatYield(summary.yield), accent: colors.green },
  ];

  const pageW = doc.internal.pageSize.getWidth();
  const x0 = 14;
  const y0 = 50;
  const gap = 10;
  const cardW = (pageW - x0 * 2 - gap) / 2;
  const cardH = 72;

  cards.forEach((c, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = x0 + col * (cardW + gap);
    const y = y0 + row * (cardH + gap);

    doc.setFillColor(colors.card);
    doc.setDrawColor(colors.border);
    doc.roundedRect(x, y, cardW, cardH, 10, 10, 'FD');

    doc.setDrawColor(c.accent);
    doc.setLineWidth(3);
    doc.line(x + 10, y + 14, x + 10, y + cardH - 14);

    doc.setFont(fvBrand.font.body, 'normal');
    doc.setFontSize(10);
    doc.setTextColor(colors.muted);
    doc.text(c.label.toUpperCase(), x + 24, y + 26);

    doc.setFont(fvBrand.font.title, 'bold');
    doc.setFontSize(16);
    doc.setTextColor(colors.text);
    doc.text(c.value, x + 24, y + 50);
  });
}

export function addChartsPage(
  doc: jsPDF,
  chartSections: Array<{ title: string; imageDataUrl?: string }>,
) {
  const { colors } = fvBrand;
  doc.addPage();
  headerBand(doc, 'Charts', 'Monthly revenue, expenses, and yield');

  let y = 48;
  const x = 14;
  const w = doc.internal.pageSize.getWidth() - 28;
  const cardH = 170;

  chartSections.forEach((s) => {
    doc.setFillColor(colors.card);
    doc.setDrawColor(colors.border);
    doc.roundedRect(x, y, w, cardH, 12, 12, 'FD');

    doc.setFont(fvBrand.font.title, 'bold');
    doc.setFontSize(12);
    doc.setTextColor(colors.text);
    doc.text(s.title, x + 14, y + 22);

    if (s.imageDataUrl) {
      try {
        doc.addImage(s.imageDataUrl, 'PNG', x + 14, y + 32, w - 28, cardH - 46, undefined, 'FAST');
      } catch {
        // ignore image failures; still export pdf
      }
    } else {
      doc.setFont(fvBrand.font.body, 'normal');
      doc.setFontSize(10);
      doc.setTextColor(colors.muted);
      doc.text('Chart unavailable', x + 14, y + 56);
    }

    y += cardH + 10;
  });
}

export function addDetailsTablePage(
  doc: jsPDF,
  title: string,
  head: string[],
  body: Array<Array<string | number>>,
) {
  doc.addPage();
  headerBand(doc, title, 'Detailed table');

  autoTable(doc, {
    startY: 38,
    head: [head],
    body,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: fvBrand.colors.green, textColor: '#FFFFFF' },
    alternateRowStyles: { fillColor: fvBrand.colors.bg },
    margin: { left: 14, right: 14 },
  });
}

export function finalizeWithFooters(doc: jsPDF) {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }
}

